# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6ecd8a36f7271621090dfe9dd65cccb6de4d7e036bc0b69a4f761a0a9f27e73448bf834596e754016825db095f4a46017a3492c0162da27ad9227de3dbb55f04

test:
  secret_key_base: cead64abf436130adb24e69e13b0c3c3e4ff6065681fef7e71b2c91a8b9b9327f92b941e98273c48fdee080d79ce6d19d7f5ca53dd48860752e5bb0cc09a3c41

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
